### PR TITLE
UF-283: Upgrade uberfire-tutorial to Java 8 and Errai UI

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by ederign** [comment]
@paulovmr please ping me after your changes! Thanks!

**Comment by paulovmr** [comment]
@ederign All done!

**Comment by ederign** [comment]
+1 @thanks paulo (I've already tested locally)
Related PRs: 
https://github.com/uberfire/uberfire/pull/312
https://github.com/uberfire/uberfire-docs/pull/10

**Comment by csadilek** [comment]
master:2f06e32e7f1c7442bd4c63dbe6b5bc5ed7a63ce0

**Pull request closed without merging**
